"""add_non_sales_columns

Revision ID: 9392c45c7884
Revises: c3d1e7f8a902
Create Date: 2026-07-04 20:02:10.982075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9392c45c7884'
down_revision: Union[str, Sequence[str], None] = 'c3d1e7f8a902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('call_type', sa.String(length=50), server_default='SALES_CALL', nullable=False))
    op.add_column('call', sa.Column('is_sales_call', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('call', sa.Column('non_sales_reason', sa.Text(), nullable=True))
    op.add_column('call', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.alter_column('call', 'processing_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('Uploaded', 'Queued', 'Processing', 'Ready For Transcription', 'Ready For Diarization', 'Ready For Transcript Merge', 'Ready For PII Redaction', 'Ready For AI Analysis', 'Completed', 'Failed', name='processingstatus', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('processing_job', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('Uploaded', 'Queued', 'Processing', 'Ready For Transcription', 'Ready For Diarization', 'Ready For Transcript Merge', 'Ready For PII Redaction', 'Ready For AI Analysis', 'Completed', 'Failed', name='processingstatus', native_enum=False, length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_job', 'status',
               existing_type=sa.Enum('Uploaded', 'Queued', 'Processing', 'Ready For Transcription', 'Ready For Diarization', 'Ready For Transcript Merge', 'Ready For PII Redaction', 'Ready For AI Analysis', 'Completed', 'Failed', name='processingstatus', native_enum=False, length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('call', 'processing_status',
               existing_type=sa.Enum('Uploaded', 'Queued', 'Processing', 'Ready For Transcription', 'Ready For Diarization', 'Ready For Transcript Merge', 'Ready For PII Redaction', 'Ready For AI Analysis', 'Completed', 'Failed', name='processingstatus', native_enum=False, length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('call', 'classification_confidence')
    op.drop_column('call', 'non_sales_reason')
    op.drop_column('call', 'is_sales_call')
    op.drop_column('call', 'call_type')
    # ### end Alembic commands ###
