"""Initial Models

Revision ID: adf9fe823186
Revises: 
Create Date: 2026-07-02 22:10:25.228174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf9fe823186'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='advisorstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('call',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('audio_file', sa.Text(), nullable=False),
    sa.Column('audio_duration', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processing_status', sa.Enum('Uploaded', 'Queued', 'Processing', 'Completed', 'Failed', name='processingstatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_advisor_id'), 'call', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_call_processing_status'), 'call', ['processing_status'], unique=False)
    op.create_index(op.f('ix_call_upload_time'), 'call', ['upload_time'], unique=False)
    op.create_table('a_i_summary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('customer_goal', sa.Text(), nullable=True),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('recommended_next_step', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('call_score',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('rapport_score', sa.Integer(), nullable=True),
    sa.Column('needs_discovery_score', sa.Integer(), nullable=True),
    sa.Column('objection_handling_score', sa.Integer(), nullable=True),
    sa.Column('product_knowledge_score', sa.Integer(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('closing_score', sa.Integer(), nullable=True),
    sa.Column('trial_booking_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_call_score_overall_score'), 'call_score', ['overall_score'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=150), nullable=False),
    sa.Column('feedback_type', sa.Enum('Score', 'Tag', 'Summary', 'Transcript', name='feedbacktype', native_enum=False, length=50), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_call_id'), 'feedback', ['call_id'], unique=False)
    op.create_table('issue_tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('Low', 'Medium', 'High', 'Critical', name='issueseverity', native_enum=False, length=20), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('speaker', sa.String(length=30), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_tag_call_id'), 'issue_tag', ['call_id'], unique=False)
    op.create_index(op.f('ix_issue_tag_category'), 'issue_tag', ['category'], unique=False)
    op.create_index(op.f('ix_issue_tag_severity'), 'issue_tag', ['severity'], unique=False)
    op.create_table('processing_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Uploaded', 'Queued', 'Processing', 'Completed', 'Failed', name='processingstatus', native_enum=False, length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('transcript',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('speaker', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_call_id'), 'transcript', ['call_id'], unique=False)
    op.create_index(op.f('ix_transcript_speaker'), 'transcript', ['speaker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_speaker'), table_name='transcript')
    op.drop_index(op.f('ix_transcript_call_id'), table_name='transcript')
    op.drop_table('transcript')
    op.drop_table('processing_job')
    op.drop_index(op.f('ix_issue_tag_severity'), table_name='issue_tag')
    op.drop_index(op.f('ix_issue_tag_category'), table_name='issue_tag')
    op.drop_index(op.f('ix_issue_tag_call_id'), table_name='issue_tag')
    op.drop_table('issue_tag')
    op.drop_index(op.f('ix_feedback_call_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_call_score_overall_score'), table_name='call_score')
    op.drop_table('call_score')
    op.drop_table('a_i_summary')
    op.drop_index(op.f('ix_call_upload_time'), table_name='call')
    op.drop_index(op.f('ix_call_processing_status'), table_name='call')
    op.drop_index(op.f('ix_call_advisor_id'), table_name='call')
    op.drop_table('call')
    op.drop_table('advisor')
    op.drop_table('team')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
